version: "3.7"
services:
  mongo:
    image: mongo
    restart: always
    network_mode: bridge
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongoDB:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    network_mode: bridge
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@172.17.0.3:27017/

volumes:
  mongoDB:
