AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sync_service_v4

  Sample SAM Template for sync_service_v4
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    Layers:
      - !Ref LayerSyncService
      - !Ref LayerTransforms
    Environment:
      Variables:
        SYNC_IMAGES_SQS_URL: !Ref SyncImagesSQS
        SYNC_STORES_SQS_URL: !Ref StoresSyncSQS
        SYNC_PRODUCT_SQS_URL: !Ref ProductSyncSQS
        SYNC_PUBLISH_SQS_URL: !Ref PublishSyncSQS

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: (Required) Enter Dev | Prod. Default is Dev.
    AllowedValues:
      - dev
      - prod

Resources:
  # SQS Queues
  SyncImagesSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SyncImagesSQS
      VisibilityTimeout: 180
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SyncImagesDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Name
          Value: SyncImagesSQS
  
  SyncImagesDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SyncImagesDLQ

  StoresSyncSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: StoresSyncSQS.fifo
      ContentBasedDeduplication: true
      FifoQueue: true
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt StoresSyncDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Name
          Value: StoresSyncSQS

  StoresSyncDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: StoresSyncDLQ.fifo
      ContentBasedDeduplication: true
      FifoQueue: true

  ProductSyncSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ProductSyncSQS.fifo
      ContentBasedDeduplication: true
      FifoQueue: true
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProductSyncDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Name
          Value: ProductSyncSQS

  ProductSyncDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ProductSyncDLQ.fifo
      ContentBasedDeduplication: true
      FifoQueue: true

  PublishSyncSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PublishSyncSQS.fifo
      ContentBasedDeduplication: true
      FifoQueue: true
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PublishSyncDLQ.Arn
        maxReceiveCount: 3
      Tags:
        - Key: Name
          Value: PublishSyncSQS

  PublishSyncDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: PublishSyncDLQ.fifo
      ContentBasedDeduplication: true
      FifoQueue: true

  # API Gateway
  SyncServiceV4Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      TracingEnabled: true

  # S3 Buckets
  SyncServiceV4Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "syncservicev4.admin.${StageName}"

  ProductBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SyncServiceV4Bucket
      PolicyDocument:
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub arn:aws:s3:::${SyncServiceV4Bucket}/*

  SyncServiceV4LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "syncservicev4.sync.${StageName}"
            
  #Lambdas
  LayerSyncService:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sync-service-layer
      Description: Shared dependencies and utils for the app
      ContentUri: src/layers/sync-service-layer/build
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x
  
  LayerTransforms:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: transforms-layer
      Description: Sync service account transformations
      ContentUri: src/layers/transforms-layer/build
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x

  CreateStores:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/CreateStores/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        SqsTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt StoresSyncSQS.Arn
            BatchSize: 5
            ScalingConfig:
               MaximumConcurrency: 20
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  CreateProduct:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/CreateProduct/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        SqsTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt ProductSyncSQS.Arn
            BatchSize: 3
            ScalingConfig:
               MaximumConcurrency: 20
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt SyncImagesSQS.Arn
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  SyncImages:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/SyncImages/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      MemorySize: 256
      Architectures:
        - x86_64
      Events:
        SqsTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt SyncImagesSQS.Arn
            BatchSize: 8
            ScalingConfig:
               MaximumConcurrency: 5
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "arn:aws:s3:::syncservicev4.admin.dev/*"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  PublishSync:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/PublishSync/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      MemorySize: 1024
      Architectures:
        - x86_64
      Events:
        SqsTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt PublishSyncSQS.Arn
            BatchSize: 1
            ScalingConfig:
               MaximumConcurrency: 2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "arn:aws:s3:::syncservicev4.sync.dev/*"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  # Gateways Lambdas
  PublishSyncValidate:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/PublishSyncValidate/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/publish-sync"
            Method: POST
            RestApiId: !Ref SyncServiceV4Api
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt PublishSyncSQS.Arn 
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  PublishWebhook:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/PublishWebhook/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/publish-webhook"
            Method: POST
            RestApiId: !Ref SyncServiceV4Api
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  SyncSummary:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/SyncSummary/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/sync-summary"
            Method: GET
            RestApiId: !Ref SyncServiceV4Api
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  FetchStoresByIdByVendor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/FetchStoresByVendor/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/stores/{storeId}"
            Method: GET
            RestApiId: !Ref SyncServiceV4Api
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  FetchStoresByVendor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/FetchStoresByVendor/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/stores"
            Method: GET
            RestApiId: !Ref SyncServiceV4Api
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  FetchProductsByIdByVendor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/FetchProductsByVendor/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/products/{productId}"
            Method: GET
            RestApiId: !Ref SyncServiceV4Api
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  FetchProductsByVendor:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/FetchProductsByVendor/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/products"
            Method: GET
            RestApiId: !Ref SyncServiceV4Api
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  ValidateLists:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/ValidateLists/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/lists"
            Method: POST
            RestApiId: !Ref SyncServiceV4Api
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt ProductSyncSQS.Arn
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "arn:aws:s3:::syncservicev4.sync.dev/*"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  ValidateProducts:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/ValidateProducts/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/products"
            Method: POST
            RestApiId: !Ref SyncServiceV4Api
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt ProductSyncSQS.Arn
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "arn:aws:s3:::syncservicev4.sync.dev/*"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  ValidateStores:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/ValidateStores/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Tracing: Active
      Architectures:
        - x86_64
      MemorySize: 256
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: "/api/v4/channels-stores"
            Method: POST
            RestApiId: !Ref SyncServiceV4Api
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt StoresSyncSQS.Arn 
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "arn:aws:s3:::syncservicev4.sync.dev/*"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SyncServiceV4Api:
    Description: "API Gateway endpoint URL for Prod stage for SyncServices Functions"
    Value: !Sub "https://${SyncServiceV4Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  SyncServiceV4Bucket:
    Description: "S3 Bucket for SyncServices"
    Value: !Sub "syncservicev4.admin.${StageName}"
  SyncServiceV4BucketARN:
    Description: "S3 Bucket for SyncServices"
    Value: !GetAtt SyncServiceV4Bucket.Arn
