AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sync_service_v4

  Sample SAM Template for sync_service_v4
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180
    Layers:
      - !Ref LayerSyncService
    Environment:
      Variables:
        SYNC_IMAGES_SQS_URL: !Ref SyncImagesSQS

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: (Required) Enter Dev | Prod. Default is Dev.
    AllowedValues:
      - dev
      - prod

Resources:
  # SQS Queues
  SyncImagesSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: SyncImagesSQS
      VisibilityTimeout: 180
      Tags:
        - Key: Name
          Value: SyncImagesSQS

  # API Gateway
  SyncServiceV4Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName

  # S3 Buckets
  SyncServiceV4Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "syncservicev4.admin.${StageName}"

  #Lambdas
  LayerSyncService:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sync-service-layer
      Description: Shared dependencies and utils for the app
      ContentUri: src/layers/sync-service-layer/build
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x

  CreateStores:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/CreateStores/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /channels-stores
            Method: POST
            RestApiId: !Ref SyncServiceV4Api
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  CreateLists:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/CreateLists/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /lists
            Method: POST
            RestApiId: !Ref SyncServiceV4Api
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt SyncImagesSQS.Arn
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  CreateProducts:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/CreateProducts/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /products
            Method: POST
            RestApiId: !Ref SyncServiceV4Api
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt SyncImagesSQS.Arn
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"

  SyncImages:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/functions/SyncImages/
      Handler: handler.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        SqsTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt SyncImagesSQS.Arn
            ScalingConfig:
              MaximumConcurrency: 10
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "arn:aws:s3:::syncservicev4.admin.dev/*"
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - handler.ts
        External:
          - "/opt/nodejs/*"


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SyncServiceV4Api:
    Description: "API Gateway endpoint URL for Prod stage for SyncServices Functions"
    Value: !Sub "https://${SyncServiceV4Api}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  SyncServiceV4Bucket:
    Description: "S3 Bucket for SyncServices"
    Value: !Sub "syncservicev4.admin.${StageName}"
  SyncServiceV4BucketARN:
    Description: "S3 Bucket for SyncServices"
    Value: !GetAtt SyncServiceV4Bucket.Arn
